[project]
name = "equirk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "numpy>=2.3.2",
    "polars>=1.32.2",
    "scikit-learn>=1.7.1",
]
